### ISSUE TITLE
TPS along with PPS

### ISSUE THREAD

**Issue by rameez707** [victorgabr/pps#3]
Can we use TPS along with PPS in same project?

**Comment by victorgabr** [comment]
Do you mean, getting the DVH calculated from a TPS instead of calculating it using PPS?

If you have a DICOM-RTDOSE file containing a DVHs exported from a TPS.

You can use the method

**GetDVHs()**

Example at the end of the module:

[https://github.com/victorgabr/pps/blob/master/pyplanscoring/core/dicom_reader.py](url)


**filename = 'RD.dcm'
rd_dcm = PyDicomParser(filename=filename)
dvhs = rd_dcm.GetDVHs()**

**Comment by rameez707** [comment]
Thanks alot
